version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - "./etc/telegraf.conf:/etc/telegraf/telegraf.conf:Z"
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - "./data/influxdb:/var/lib/influxdb:Z"
    ports:
      - "8086:8086"
  # Define a Chronograf service
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.3.5
    entrypoint:
      - influx
      - -host
      - influxdb
